### PR TITLE
W10 default restore and .gitignore for .vscode/

### PR DESCRIPTION
**Pull request by rbeesley**
Added W10 registry file so that the user can restore to default settings... not that there has been any difference for these values. Also added to .gitignore to ignore .vscode/ since I used VSCode as my editor and it creates a .vscode user setting directory which should not be part of the project.

### CODE REVIEW

**Comment by neilpa** [comment]
I don't have the ability to test these anymore (no access to a Win10 box) but it looks reasonable. Would you mind also adding a quick note to the README after the install section pointing out default regfiles for restoring.

**Comment by rbeesley** [comment]
Updated the `README.md` to include  brief uninstall information. As the only differences between the `win*-defaults.reg` files were the order of the keys, which are unimportant when importing, they have been combined into a single `windows-defaults.reg`. The line endings for the `*.reg` files have been converted to `CRLF` to conform with what Windows expects and organized to match across all 3 files. Removed `test=auto` from `.gitattributes` which automatically converted all files to `LF` line endings.

These are more changes than you requested, but I believe this will leave the repository in a better state.

**Comment by rbeesley** [comment]
Did not mean to close...

**Comment by neilpa** [comment]
> These are more changes than you requested, but I believe this will leave the repository in a better state.

Thanks for combining these things 👍

**Pull request merged**
