### PR TITLE
Feature/update for start menu

### PR DESCRIPTION
**Pull request by theunrepentantgeek**
Every time I get a new build of windows (I'm on the Windows Insider Fast Ring), I need to restore use of the solarized palette as the update resets them to the standard colours. This script makes that chore a little easier.

### CODE REVIEW

**Comment by rbeesley** [comment]
Follow the example of [Update-Link.cmd](../blob/master/Update-Link.cmd) and add a Update-StartMenu.ps1, this way Execution Policies can be left unchanged. (Psst, you can just copy and rename the Update-Link.cmd to Update-StartMenu.ps1)

**Comment by theunrepentantgeek** [comment]
Good idea, done.
(Though, I had to Google how the `%~dpn0.ps1` worked. 😄)

**Comment by theunrepentantgeek** [comment]
Anything you need from me before you merge this PR?

**Comment by neilpa** [comment]
Sorry about the delay @theunrepentantgeek. I don't pay close attention to this repo anymore since I haven't used Windows as my daily driver for years. This looks good though.

**Comment by theunrepentantgeek** [comment]
Thanks!

**Pull request merged**
